"""Report generation agent: human-readable operational reports from structured evidence.

Kinds: EXPERIMENT_SUMMARY, INCIDENT_REPORT, MODEL_COMPARISON, AUDIT_EXPLANATION.
Report generation time is measured for the efficiency metric."""
from __future__ import annotations
import time
from .base import Agent
from .schemas import AgentOutput, AgentQuery

REPORT_KINDS = {"EXPERIMENT_SUMMARY", "INCIDENT_REPORT", "MODEL_COMPARISON", "AUDIT_EXPLANATION"}


class ReportGenerationAgent(Agent):
    agent_id = "REPORT_GENERATION_AGENT"
    agent_version = "1.0.0"

    def analyze(self, query: AgentQuery) -> AgentOutput:
        started = time.perf_counter()
        kind = query.payload.get("report_kind", "")
        refs = [str(x) for x in query.payload.get("evidence_refs", [])]
        if kind not in REPORT_KINDS:
            return AgentOutput(
                agent_id=self.agent_id, agent_version=self.agent_version, query_id=query.query_id,
                input_evidence_refs=[], reasoning_summary=f"Unknown report kind '{kind}'.",
                recommendation="EXPLAIN", recommendation_text=f"Choose one of {sorted(REPORT_KINDS)}.",
                confidence=0.2, limitations="Missing evidence handled gracefully.",
                requires_human_review=False, query_type=query.query_type,
                advisory_text_untrusted="")
        sections = {
            "EXPERIMENT_SUMMARY": self._experiment_summary(query.payload),
            "INCIDENT_REPORT": self._incident(query.payload),
            "MODEL_COMPARISON": self._comparison(query.payload),
            "AUDIT_EXPLANATION": self._audit(query.payload),
        }[kind]
        elapsed = time.perf_counter() - started
        body = f"# {kind.replace('_', ' ').title()}\n\n" + "\n\n".join(sections) + \
            f"\n\n_Generated by REPORT_GENERATION_AGENT (deterministic, advisory; generation time {elapsed:.4f}s)._"
        return AgentOutput(
            agent_id=self.agent_id, agent_version=self.agent_version, query_id=query.query_id,
            input_evidence_refs=refs, reasoning_summary=f"{kind} produced from structured evidence in {elapsed:.4f}s.",
            recommendation="CREATE_REPORT", recommendation_text=body, confidence=0.9,
            limitations=("Reports restate recorded evidence deterministically; they contain no forecasts of future "
                         "performance and cannot trigger lifecycle actions."),
            requires_human_review=False, query_type=query.query_type)

    def _experiment_summary(self, payload: dict) -> list[str]:
        rows = payload.get("adaptation_rows", [])
        lines = [f"- {r.get('target', '?')} / {r.get('scenario', '?')}: reference MAE "
                 f"{r.get('reference_mae', '?')}, challenger MAE {r.get('challenger_mae', '?')}, "
                 f"adaptation gain {r.get('adaptation_gain_percent', '?')}%" for r in rows] or ["- no rows supplied"]
        return ["## Adaptation experiment results (development/simulation)",
                "\n".join(lines),
                f"Total scenarios reported: {len(rows)}."]

    def _incident(self, payload: dict) -> list[str]:
        event = payload.get("drift_event", {})
        decision = payload.get("retraining_decision", {})
        return ["## Drift incident",
                f"- Target: {event.get('target', '?')}; scenario {event.get('scenario_id', '?')}; "
                f"severity {event.get('severity', '?')}; detectors {', '.join(event.get('triggered', [])) or 'none'}.",
                "## Governance response",
                f"- Retraining decision: {decision.get('decision', 'not recorded')}; "
                f"reasons: {', '.join(decision.get('reason_codes', [])) or 'none'}.",
                "Drift is observational evidence; no lifecycle action follows without a governed decision."]

    def _comparison(self, payload: dict) -> list[str]:
        evaluations = payload.get("challenger_evaluations", [])
        lines = [f"- {e.get('challenger_id', '?')}: decision {e.get('decision', '?')} "
                 f"(reasons: {', '.join(e.get('reason_codes', [])) or 'none'})" for e in evaluations] or ["- none supplied"]
        return ["## Challenger promotion evaluations",
                "\n".join(lines),
                "Improved MAE alone is not sufficient: benchmark and approval gates decide promotion."]

    def _audit(self, payload: dict) -> list[str]:
        events = payload.get("audit_events", [])
        lines = [f"- {e.get('event_type', '?')} on {e.get('subject_id', '?')} (actor {e.get('actor_type', '?')})"
                 for e in events] or ["- none supplied"]
        return ["## Recent audited actions", "\n".join(lines),
                f"Total events explained: {len(events)}."]
