"""Stage 2 thin FastAPI service layer.

This package is a pure adapter over the Stage 1 productization contract
(smartgrid_mlops.productization) and the existing research artefacts. It
contains NO business logic of its own: every endpoint either calls a
productization function or reads an existing research JSON / CSV / YAML.
The service is read-only and advisory-only. Lifecycle mutations are NOT
exposed as endpoints; agents can recommend, the governance engine
authorizes.

The 7 routers (one per route group) follow the OpenAPI documentation
generated by FastAPI; Pydantic models in app.schemas represent the existing
domain types (no new fabricated fields).

No quantum / QML / GNN / LLM. No Redis / Kafka / Celery / K8s. No fake
real-time infrastructure. This is an offline evaluation system.
"""
from .main import create_app

__all__ = ["create_app"]
