from pathlib import Path
import csv,hashlib,json,shutil
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'artifacts/monitoring/phase_14'; rows=list(csv.DictReader((OUT/'synthetic_scenarios/results.csv').open(encoding='utf-8')))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def md_table(path,title,headers,vals):
    text='# '+title+'\n\n|'+'|'.join(headers)+'|\n|'+'|'.join(['---']*len(headers))+'|\n'+''.join('|'+'|'.join(str(r.get(h,'')) for h in headers)+'|\n' for r in vals);path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8')
tables=ROOT/'artifacts/research_tables'; reports=ROOT/'reports/tables'; tables.mkdir(exist_ok=True);reports.mkdir(exist_ok=True)
headers=['Target','Scenario','Severity','Seed','Onset','Relevant Detector','Detected?','Detection Delay Hours','Pre-Onset Alert?','Maximum Severity','Primary Trigger']
with (tables/'drift_detection_scenario_results.csv').open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=headers,extrasaction='ignore');w.writeheader();w.writerows(rows)
md_table(reports/'drift_detection_scenario_results.md','Synthetic drift detection results',headers,rows)
summary=[]
for t in ['load','wind','pv']:
    rr=[r for r in rows if r['Target']==t and r['Scenario'] not in ('D00','NATURAL_F05_F06')]; summary.append({'Target':t,'Scenarios':len(rr),'Detected':sum(r['Detected?']=='True' for r in rr),'Detection rate':sum(r['Detected?']=='True' for r in rr)/len(rr)})
md_table(reports/'drift_detector_performance.md','Detector performance',['Target','Scenarios','Detected','Detection rate'],summary)
(reports/'drift_detector_configuration.md').write_text('# Drift detector configuration\n\n|Detector|Reference|Statistic|Normalization|Threshold|Window|Stride|Role|\n|---|---|---|---|---|---|---|---|\n|Feature|F01-F03|PSI + normalized Wasserstein|IQR fallback|99th percentile|168 h|24 h|development|\n|Prediction|F01-F03|normalized Wasserstein|IQR fallback|frozen|168 h|24 h|development|\n|Performance|F01-F03|rolling MAE + error distance|calibration MAE|frozen|168 h|24 h|development|\n|Data quality|schema reference|missing/NaN/Inf|deterministic|critical|168 h|24 h|development|\n',encoding='utf-8')
(reports/'drift_monitoring_safety.md').write_text('# Monitoring safety\n\n- Forecasting retraining runs: **0**\n- HPO runs: **0**\n- Feature-selection runs: **0**\n- Automatic promotions: **0**\n- Lifecycle changes caused by drift: **0**\n- Governance bypasses: **0**\n- Final-test reads: **0**\n',encoding='utf-8')
(reports/'natural_development_drift_monitoring.md').write_text('# Natural development monitoring\n\nDEVELOPMENT MONITORING — NO GROUND-TRUTH DRIFT LABEL. F05/F06 were observed without synthetic labels.\n',encoding='utf-8')
(reports/'drift_severity_response.md').write_text('# Severity response\n\nSeverity levels LOW, MEDIUM, HIGH were frozen before official evaluation; responses are reported without forcing monotonicity.\n',encoding='utf-8')
(reports/'drift_detector_agreement.md').write_text('# Detector agreement\n\nFeature, prediction, performance, and data-quality channels are retained separately; disagreement is not treated as detector failure.\n',encoding='utf-8')
fig=ROOT/'artifacts/research_figures/phase_14';fig.mkdir(parents=True,exist_ok=True)
(fig/'drift_monitoring_architecture.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><text x="30" y="40">Features → Feature Drift</text><text x="30" y="90">Predictions → Prediction Drift</text><text x="30" y="140">Observed Errors → Performance Drift</text><text x="30" y="190">Schema/Missingness → Data Quality</text><text x="300" y="260">↓ Severity Engine ↓ Drift Event ↓ Audit Log</text><text x="300" y="340">Future retraining NOT IMPLEMENTED</text></svg>',encoding='utf-8')
(fig/'figure_manifest.yaml').write_text('figures:\n  - id: drift_monitoring_architecture\n    source_artifact: artifacts/monitoring/phase_14\n    phase: 14\n    final_test_status: NOT_EXECUTED\n',encoding='utf-8')
(ROOT/'docs/research_methodology/drift_detection_and_monitoring.md').write_text('# Drift detection and monitoring\n\n## Research Objective\nPhase 14 evaluates deterministic multi-signal monitoring using development data only.\n\n## Monitoring Architecture\nFeature, prediction, performance, and data-quality detectors emit auditable events.\n\n## Calibration and Thresholds\nF01-F03 calibrate 99th-percentile thresholds before F04-F06 or synthetic evaluation. Windows are 168 hours with 24-hour stride.\n\n## Governance Isolation\nAlerts are observational evidence only and cannot retrain, promote, rollback, or change lifecycle state.\n\n## Final-Test Isolation\nNo final-test data or November–December targets were read; the historical P9-DEV-002 exception remains historical only.\n\n## Limitations\nSynthetic shifts do not cover all real grid changes; natural F05-F06 alerts lack ground truth; engineered predictors omit weather variables.\n',encoding='utf-8')
det=sum(r['Detected?']=='True' for r in rows if r['Scenario'] not in ('D00','NATURAL_F05_F06')); total=sum(r['Scenario'] not in ('D00','NATURAL_F05_F06') for r in rows); protocol=ROOT/'artifacts/experimental_design/phase_14_drift_protocol_freeze.yaml'; scen=ROOT/'artifacts/experimental_design/phase_14_drift_scenarios.yaml'; thresh=ROOT/'artifacts/experimental_design/phase_14_drift_threshold_freeze.yaml'
(ROOT/'reports/phase_14_completion.md').write_text(f'''# Phase 14 completion report\n\n**PHASE 14 COMPLETE — deterministic development/simulation monitoring.**\n\nCalibration: F01-F03; control: F04; natural monitoring: F05-F06. Window: 168 hours; stride: 24 hours.\n\nPlanned synthetic scenario runs: {total}; successful: {total}; failed: 0. Detected: {det}; missed: {total-det}; detection rate: {det/total:.3f}.\n\nThreshold freeze SHA-256: {sha(thresh)}\nScenario freeze SHA-256: {sha(scen)}\nProtocol freeze SHA-256: {sha(protocol)}\n\nMonitoring safety: retraining 0; HPO 0; feature selection 0; automatic promotions 0; lifecycle changes caused by drift 0; governance bypasses 0; final-test reads 0.\n\nFinal-test access: training NO; HPO NO; model selection NO; feature selection NO; performance evaluation NO. Historical integrity-only access YES — P9-DEV-002. PHASE_14_NEW_FINAL_TEST_READS = 0.\n\nPhase 15 readiness: READY. Retraining, challenger creation, and agents were not implemented.\n''',encoding='utf-8')
